### PR TITLE
EN6-34

### PR DESCRIPTION
**Pull request by sergiofilhowz**

### CODE REVIEW

**Comment by entando-service** [comment]
All is well

**Review by ampie — CHANGES_REQUESTED** [review]
I think this project is getting big enough to get some tests in place. I think unit tests would suffice, and don't worry too much about coverage. Just write some tests for logic that can be tested in isolation.

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Review by ampie — APPROVED** [review]

**Pull request merged**
